; Common PHP settings for all environments
max_execution_time = 90
memory_limit = 512M

session.cookie_lifetime = 86400
session.gc_maxlifetime = 86400
session.cookie_samesite = None

error_reporting = E_ALL & ~E_STRICT
