services:
  db:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d:ro
      - postgresql17:/var/lib/postgresql/data

  author-be:
    build:
      context: .
      target: dev
      dockerfile: docker/backend/Dockerfile
      args:
        UID: ${USER_ID:-48}
        GID: ${GROUP_ID:-48}
      cache_from:
        - type=gha,scope=dev-backend
      cache_to:
        - type=gha,scope=dev-backend,mode=max
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - type: bind
        source: .
        target: /app/author
      - type: volume
        source: vendor
        target: /app/author/vendor
      - type: volume
        source: var
        target: /app/author/var
      - type: volume
        source: fonts
        target: /app/author/fonts
    depends_on:
      - db

  author-fe:
    build:
      context: .
      target: dev
      dockerfile: docker/frontend/Dockerfile
      cache_from:
        - type=gha,scope=dev-frontend
      cache_to:
        - type=gha,scope=dev-frontend,mode=max
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    ports:
      - 8080:8080
    depends_on:
      - author-be

volumes:
  postgresql17:
  fonts:
  var:
  vendor:
