commands:
    - GisClient\Author\Command\CreateSqliteCommand
    - GisClient\Author\Command\DbUpgradeCommand
    - GisClient\Author\Command\ProjectExportCommand
    - GisClient\Author\Command\ProjectImportCommand
    - GisClient\Author\Command\DataExportCommand
    - GisClient\Author\Command\DataImportCommand
    - GisClient\Author\Command\RefreshMapfileCommand
