commands:
    - GisClient\Author\Command\CreateSqliteCommand
    - GisClient\Author\Command\DbUpgradeCommand
    - GisClient\Author\Command\ProjectExportCommand
    - GisClient\Author\Command\ProjectImportCommand
    - GisClient\Author\Command\SymbolExportCommand
    - GisClient\Author\Command\SymbolImportCommand
    - GisClient\Author\Command\FontExportCommand
    - GisClient\Author\Command\FontImportCommand
    - GisClient\Author\Command\RefreshMapfileCommand
