services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GisClient\Author\Offline\LookupData:
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\MapData:
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\MbtilesData:
    arguments: ['%mapproxy_dir%/bin', '%project_dir%/map', '%debug_dir%']
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\MVTData:
    arguments: ['%debug_dir%']
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\SavedFilterData:
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\SqliteData:
    arguments: ['%debug_dir%']
    tags: ['gisclient.offline_data_format']
  GisClient\Author\Offline\ThemeLegendData:
    tags: ['gisclient.offline_data_format']
  GisClient\Author\OfflineMap:
    public: true
    arguments:
      $offlineDataFormats: !tagged gisclient.offline_data_format
  GisClient\Author\Utils\TemporaryFileService:
    arguments: ['%tmp_dir%']

  GisClient\Author\Persistence\EntityRepository:
    class: GisClient\Author\Persistence\PdoEntityRepository

  GisClient\Author\Api\Serializer\JsonApiSerializer:
    public: true

  GisClient\Author\Api\Mapper\JsonApiExceptionMapper:
    public: true

  GisClient\Author\Api\Gateway\ApiCrudGatewayInterface:
    class: GisClient\Author\Api\Gateway\ApiCrudServiceGateway
    public: true

  GisClient\Author\Api\Service\ApiCrudService:
    public: true

  GisClient\Author\Api\Service\ProjectCopyService:
    public: true

  GisClient\Author\Api\Service\ProjectTransferService:
    public: true

  GisClient\Author\Api\Service\ProjectExportService:
    public: true

  GisClient\Author\Api\Service\ProjectImportService:
    public: true

  GisClient\Author\Api\Service\SymbolExportService:
    public: true

  GisClient\Author\Api\Service\SymbolImportService:
    public: true

  GisClient\Author\Api\Service\FontExportService:
    public: true

  GisClient\Author\Api\Service\FontImportService:
    public: true

  GisClient\Author\Api\Serializer\DtoSerializer:
    public: true

  Symfony\Component\Config\FileLocator:
    arguments: ['%project_dir%/config']
  Symfony\Component\Routing\Loader\YamlFileLoader:
    arguments: ['@Symfony\Component\Config\FileLocator']
  Symfony\Component\Routing\Router:
    arguments: ['@Symfony\Component\Routing\Loader\YamlFileLoader', 'routing.yml']
    public: true
