## Available routes in public/services/...
gcmap:
    path: gcmap.php
    defaults:  { _controller: GisClient\Author\Controller\ClientController::gcmapAction }
    
gcmapConfig:
    path: gcmapconfig.php
    defaults:  { _controller: GisClient\Author\Controller\ClientController::gcmapConfigAction }
    