## Available routes in public/services/...
login:
    path: login
    defaults:  { _controller: GisClient\Author\Controller\LoginController::loginAction }
    methods:  [POST]
logout:
    path: logout
    defaults:  { _controller: GisClient\Author\Controller\LoginController::logoutAction }
    methods:  [GET]
autocomplete:
    path: autocomplete.php
    defaults:
        _controller: 'GisClient\Author\Controller\AutocompleteController::autocompleteAction'
    methods:
        - GET
createImage:
    path: download.php
    defaults:
        _controller: 'GisClient\Author\Controller\DownloadController::createImageAction'
    methods:
        - POST
gcmap:
    path: gcmap.php
    defaults:  { _controller: GisClient\Author\Controller\ClientController::gcmapAction }
    
gcmapConfig:
    path: gcmapconfig.php
    defaults:  { _controller: GisClient\Author\Controller\ClientController::gcmapConfigAction }

refreshMapfile:
    path: refresh_mapfile
    defaults: { _controller: GisClient\Author\Controller\RefreshMapfileController::refreshMapfileAction }
    methods: [POST]

## Saved filter routes
getAllSavedFilter:
    path: saved_filter/{mapset}
    defaults:  { _controller: GisClient\Author\Controller\SavedFilterController::getAllAction }
    methods:  [GET]

createSavedFilter:
    path: saved_filter
    defaults:  { _controller: GisClient\Author\Controller\SavedFilterController::createAction }
    methods:  [POST]
    
modifySavedFilter:
    path: saved_filter/{id}
    defaults:  { _controller: GisClient\Author\Controller\SavedFilterController::modifyAction }
    methods:  [PUT]
    requirements:
        id: \d+

deleteSavedFilter:
    path: saved_filter/{id}
    defaults:  { _controller: GisClient\Author\Controller\SavedFilterController::deleteAction }
    methods:  [DELETE]
    requirements:
        id: \d+
