dbobjects:
    #tables
    - authfilter
    - catalog
    - catalog_import
    - class
    - document
    - e_charset_encodings
    - e_conntype
    - e_datatype
    - e_fieldformat
    - e_fieldtype
    - e_filetype
    - e_form
    - e_formula
    - e_language
    - e_layertype
    - e_lblposition
    - e_legendtype
    - e_level
    - e_orderby
    - e_outputformat
    - e_owstype
    - e_papersize
    - e_pattern
    - e_relationtype
    - e_resultype
    - e_searchable
    - e_searchtype
    - e_sizeunits
    - e_symbolcategory
    - e_tiletype
    - e_wmsversion
    - export_i18n
    - field
    - field_groups
    - font
    - form_level
    - group_authfilter
    - groups
    - i18n_field
    - layer
    - layer_authfilter
    - layer_groups
    - layer_link
    - layergroup
    - link
    - localization
    - logs
    - mapset
    - mapset_groups
    - mapset_layergroup
    - project
    - project_admin
    - project_languages
    - project_srs
    - qt
    - qt_field
    - qt_link
    - qt_relation
    - relation
    - saved_filter
    - selgroup
    - selgroup_layer
    - sessions
    - style
    - symbol
    - theme
    - theme_version
    - user_group
    - usercontext
    - users
    - users_options
    - version
    #sequences
    - document_doc_id_seq
    - e_pattern_pattern_id_seq
    - i18n_field_i18nf_id_seq
    - layer_groups_seq
    - localization_localization_id_seq
    - logs_log_id_seq
    - saved_filter_saved_filter_id_seq
    - theme_version_id_seq
    - usercontext_usercontext_id_seq
    - users_options_users_options_id_seq
    - version_version_id_seq
    #views
    - elenco_form
    - seldb_catalog
    - seldb_catalog_wms
    - seldb_charset_encodings
    - seldb_conntype
    - seldb_datatype
    - seldb_fieldtype
    - seldb_filetype
    - seldb_font
    - seldb_group_authfilter
    - seldb_language
    - seldb_layer_layergroup
    - seldb_layertype
    - seldb_lblposition
    - seldb_legendtype
    - seldb_link
    - seldb_mapset_srid
    - seldb_mapset_tiles
    - seldb_orderby
    - seldb_outputformat
    - seldb_owstype
    - seldb_papersize
    - seldb_pattern
    - seldb_project
    - seldb_qt
    - seldb_qt_relation
    - seldb_qt_relationtype
    - seldb_relation
    - seldb_relationtype
    - seldb_resultype
    - seldb_searchable
    - seldb_searchtype
    - seldb_sizeunits
    - seldb_theme
    - seldb_tiletype
    - seldb_wmsversion
    - vista_catalog
    - vista_class
    - vista_document_paths
    - vista_field
    - vista_group_authfilter
    - vista_layer
    - vista_layergroup
    - vista_link
    - vista_mapset
    - vista_project_languages
    - vista_relation
    - vista_style
    - vista_version
